task: LaMP_2_movie
mode: dev
use_profile: True
train_dir: <TRAIN_DATA_PATH>
eval_history: <TEST_HISTORY_DATA_PATH>
eval_query: <TEST_QUERY_DATA_PATH>
partial_data:
  users: 500
retriever:
  num_retrieve: 10
  num_retrieve_user: -1
  model: bm25
  is_ranked: True
  max_length: 1024
  tokenizer: None
generator:
  model_name: gpt
  tokenizer_name: gpt
  max_length: 64
  data_frac: 0
  frac_len: 0
  output_dir: <OUTPUT_PATH>
  batch_size: 8
  token: <HUGGINGFACE_TOKEN>
  seed: 42
  temperature: 0
  tp_per_worker: 1
  num_data_frac: 1
  num_return_sequences: 1
  frequency_penalty: 0 
  presence_penalty: 0 
  stop: None
  openai_credentials: <CREDENTIALS_CONFIG>